project_id = "mjfzxmpscndznuaeoxft"

[functions.shop-config]
verify_jwt = false

[functions.analytics]
verify_jwt = false

[functions.upsells]
verify_jwt = false

[functions.billing]
verify_jwt = false