project_id = "mjfzxmpscndznuaeoxft"

[functions.app-proxy]
verify_jwt = false

[functions.cart-settings-generator]
verify_jwt = false

[functions.cart-settings-publisher]
verify_jwt = false

[functions.shop-config]
verify_jwt = false

[functions.analytics]
verify_jwt = false

[functions.addons]
verify_jwt = false

[functions.billing]
verify_jwt = false

[functions.products-proxy]
verify_jwt = false