# Learn more about configuring your Shopify app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sticky-cart-drawer"
client_id = "YOUR_CLIENT_ID_HERE"
application_url = "https://your-app-domain.vercel.app"
embedded = true

[access_scopes]
# https://shopify.dev/docs/api/usage/access-scopes
scopes = "write_products,write_themes,write_script_tags,read_products,read_orders,write_metafields,read_metafields"

[auth]
redirect_urls = [
  "https://your-app-domain.vercel.app/auth/callback",
  "https://your-app-domain.vercel.app/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://your-dev-store.myshopify.com"
include_config_on_deploy = true