# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "890d25824f8641ccb2c9beece66d5dc1"
name = "sticky-cart-drawer"
application_url = "https://sticky-cart-flow.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dimestore-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes,write_script_tags,read_products,read_orders"

[auth]
redirect_urls = [
  "https://sticky-cart-flow.vercel.app/auth/callback",
  "https://sticky-cart-flow.vercel.app/auth/shopify/callback"
]

[pos]
embedded = false
